language: cpp
compiler:
  - g++

# Setup different environments to test
env:
  - CPP14=1

# Setup repos etc before installation
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

# Install dependencies
install:
  # install g++ 4.8, if tests are run with g++
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi

script:
  ./configure -n && make

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: 8ca003e4-2371-450f-8c8e-e2fb4bff43c5
  app: condorlang